name: Quality Gate

on:
  push:
    branches: [ main ]
  pull_request:

env:
  NODE_VERSION: '20'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build

  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: npm install
      - name: Run unit tests
        run: npm test -- --runInBand
      - name: Run end-to-end smoke tests
        run: npm run e2e

  coverage:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - uses: grafana/setup-k6-action@v1
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Run coverage suite
        run: npm test -- --runInBand
      - name: Start preview server
        run: npm run preview -- --host 0.0.0.0 --port 4173 &
      - name: Wait for preview
        run: npx wait-on http://127.0.0.1:4173
      - name: Execute load testing
        run: npm run load
      - name: Publish quality report
        env:
          AUDIT_BACKEND_URL: ${{ secrets.AUDIT_BACKEND_URL }}
        run: npm run report:quality
      - name: Stop preview server
        if: always()
        run: pkill -f "vite preview" || true

  deploy:
    runs-on: ubuntu-latest
    needs: coverage
    steps:
      - name: Await quality gate
        run: echo "All gates passed. Ready to deploy."
