name: NEXUS Backend CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: nexus123
          POSTGRES_DB: nexusdb
        ports: ['5432:5432']
      redis:
        image: redis:7
        ports: ['6379:6379']
      rabbitmq:
        image: rabbitmq:3-management
        ports: ['5672:5672', '15672:15672']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || pip install .[dev]
      - name: Lint/Type/Sec
        working-directory: backend
        run: |
          ruff check .
          mypy app || true
          bandit -r app -q || true
          pip-audit || true
      - name: Tests
        working-directory: backend
        run: |
          pytest -q --cov=app --cov-report=xml
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: backend/coverage.xml
